spring.application.name=invsoft
spring.datasource.url=jdbc:postgresql://db.iquiulafrtfjojkqwfzs.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=zuevzEUByoF6TIou
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=${ADMIN_USER:admin}
spring.security.user.password=${ADMIN_PASSWORD:010200_00_Cv}
spring.jpa.show-sql=true